import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.NoncommProd
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.Subgroup.Simple
import Mathlib.Order.Atoms
import Mathlib.Order.Preorder.Finite

/-!
# Maximality of the product supplement

This module kernel-checks manuscript Lemma 3.3 conditional on the normalized
coordinate-action data isolated in the coordinate-reduction obligation.  It
proves the normal-saturation/Goursat product step, recovers coordinate-closure
stability from the stabilizer components and inner automorphisms, derives the
projection dichotomy, transports it back to every ambient overgroup, and
concludes that the coordinate-product normalizer is a coatom.
-/

namespace Kourovka1034

/-- Equal finite cardinalities turn an inclusion into equality, represented
here at the level of finite sets. -/
theorem finset_eq_of_subset_of_card_eq
    {α : Type} [DecidableEq α] {A B : Finset α}
    (hAB : A ⊆ B) (hcard : A.card = B.card) : A = B := by
  exact Finset.eq_of_subset_of_card_le hAB hcard.ge

/-- The manuscript's exact normal-saturation condition: the normal closure of
`V` in every overgroup `W` is all of `W`. -/
def NormallySaturating {S : Type*} [Group S] (V : Subgroup S) : Prop :=
  ∀ (W : Subgroup S) (_hVW : V ≤ W),
    Subgroup.normalClosure (V.subgroupOf W : Set W) = ⊤

/-- An `X`-stable conjugacy class, in the elementwise orientation used by the
coordinate-action formalization. -/
def StableSubgroupClass {S : Type*} [Group S]
    (X : Subgroup (MulAut S)) (W : Subgroup S) : Prop :=
  ∀ a : MulAut S, a ∈ X → ∃ s : S, ∀ y : S,
    y ∈ W ↔ s⁻¹ * a y * s ∈ W

/-- Stability of a subgroup class propagates to its normalizer. -/
theorem stable_normalizer
    {S : Type*} [Group S] (X : Subgroup (MulAut S)) (W : Subgroup S)
    (hstable : StableSubgroupClass X W) :
    StableSubgroupClass X (Subgroup.normalizer (W : Set S)) := by
  intro a ha
  obtain ⟨s, hs⟩ := hstable a ha
  let b : MulAut S := MulAut.conj s⁻¹ * a
  have hb (y : S) : y ∈ W ↔ b y ∈ W := by
    simpa [b, MulAut.mul_apply, mul_assoc] using hs y
  have hbW : W.map b.toMonoidHom = W := by
    ext y
    rw [Subgroup.mem_map_equiv]
    simpa using hb (b.symm y)
  have hbN : (Subgroup.normalizer (W : Set S)).map b.toMonoidHom =
      Subgroup.normalizer (W : Set S) := by
    rw [Subgroup.map_equiv_normalizer_eq, hbW]
  refine ⟨s, ?_⟩
  intro y
  have hy : y ∈ Subgroup.normalizer (W : Set S) ↔
      b y ∈ Subgroup.normalizer (W : Set S) := by
    constructor
    · intro h
      rw [← hbN]
      exact ⟨y, h, rfl⟩
    · intro h
      rw [← hbN] at h
      simpa using h
  simpa [b, MulAut.mul_apply, mul_assoc] using hy

/-- Stability under a set of automorphisms extends to the subgroup they
generate.  This is the formal closure step used when the coordinate closure
`X` is generated by stabilizer components and inner automorphisms. -/
theorem stableSubgroupClass_closure
    {S : Type*} [Group S] (W : Subgroup S) (Y : Set (MulAut S))
    (hY : ∀ a ∈ Y, ∃ s : S, ∀ y : S,
      y ∈ W ↔ s⁻¹ * a y * s ∈ W) :
    StableSubgroupClass (Subgroup.closure Y) W := by
  intro a ha
  let P : MulAut S → Prop := fun a => ∃ s : S, ∀ y : S,
    y ∈ W ↔ s⁻¹ * a y * s ∈ W
  change P a
  apply Subgroup.closure_induction (k := Y) (p := fun a _ => P a) hY
  · refine ⟨1, ?_⟩
    intro y
    simp
  · intro a b _ _
    rintro ⟨sa, ha⟩ ⟨sb, hb⟩
    refine ⟨a sb * sa, ?_⟩
    intro y
    calc
      y ∈ W ↔ sb⁻¹ * b y * sb ∈ W := hb y
      _ ↔ sa⁻¹ * a (sb⁻¹ * b y * sb) * sa ∈ W := ha _
      _ ↔ (a sb * sa)⁻¹ * (a * b) y * (a sb * sa) ∈ W := by
        simp [MulAut.mul_apply, mul_assoc]
  · intro a _
    rintro ⟨s, hs⟩
    refine ⟨(a.symm s)⁻¹, ?_⟩
    intro y
    have h := (hs (a.symm (s * y * s⁻¹))).symm
    simpa [mul_assoc] using h
  exact ha

/-- Exact actual-overgroup formulation of maximality in the manuscript's
poset of proper, self-normalizing, `X`-stable classes. -/
def PosetMaximalStableSelfNormalizing
    {S : Type*} [Group S] (X : Subgroup (MulAut S)) (V : Subgroup S) : Prop :=
  ∀ U : Subgroup S, V ≤ U → U ≠ ⊤ →
    Subgroup.normalizer (U : Set S) = U → StableSubgroupClass X U → U = V

/-- Formal normalizer-tower argument from manuscript Lemma 3.3.

In a finite simple group, a nontrivial `X`-stable overgroup of a poset-maximal
self-normalizing class is either that class or the whole group.  Rather than
choosing an arbitrary-length tower, the proof chooses a maximal proper stable
overgroup and shows its normalizer equals itself. -/
theorem stable_overgroup_eq_or_top
    {S : Type*} [Group S] [Finite S] [IsSimpleGroup S]
    (X : Subgroup (MulAut S)) (V W : Subgroup S)
    (hVbot : V ≠ ⊥) (hVW : V ≤ W)
    (hWstable : StableSubgroupClass X W)
    (hmax : PosetMaximalStableSelfNormalizing X V) :
    W = V ∨ W = ⊤ := by
  by_cases hWtop : W = ⊤
  · exact Or.inr hWtop
  · left
    letI : Finite (Subgroup S) :=
      Finite.of_injective (fun H : Subgroup S => (H : Set S)) SetLike.coe_injective
    let P : Subgroup S → Prop :=
      fun U => W ≤ U ∧ U ≠ ⊤ ∧ StableSubgroupClass X U
    have hPnonempty : Set.Nonempty {U : Subgroup S | P U} :=
      ⟨W, le_rfl, hWtop, hWstable⟩
    obtain ⟨U, hUP, hUmax⟩ :=
      Set.toFinite {U : Subgroup S | P U} |>.exists_maximal hPnonempty
    have hVU : V ≤ U := hVW.trans hUP.1
    have hUbot : U ≠ ⊥ := by
      intro h
      apply hVbot
      exact le_bot_iff.mp (hVU.trans_eq h)
    have hNproper : Subgroup.normalizer (U : Set S) ≠ ⊤ := by
      intro htop
      haveI : U.Normal := Subgroup.normalizer_eq_top_iff.mp htop
      rcases (inferInstance : U.Normal).eq_bot_or_eq_top with hbot | htop'
      · exact hUbot hbot
      · exact hUP.2.1 htop'
    have hNP : P (Subgroup.normalizer (U : Set S)) := by
      exact ⟨hUP.1.trans Subgroup.le_normalizer, hNproper,
        stable_normalizer X U hUP.2.2⟩
    have hUN : U = Subgroup.normalizer (U : Set S) :=
      le_antisymm Subgroup.le_normalizer (hUmax hNP Subgroup.le_normalizer)
    have hUV : U = V := hmax U hVU hUP.2.1 hUN.symm hUP.2.2
    exact le_antisymm (hUP.1.trans_eq hUV) hVW

/-- The homomorphism placing one element in coordinate `i` and the identity in
all other coordinates. -/
def coordinateSingletonHom
    {S I : Type*} [Group S] [DecidableEq I] (i : I) : S →* (I → S) :=
  MonoidHom.mulSingle (fun _ : I => S) i

/-- The `i`th projection of a subgroup of a direct power. -/
def coordinateProjection
    {S I : Type*} [Group S] (T : Subgroup (I → S)) (i : I) : Subgroup S :=
  T.map (Pi.evalMonoidHom (fun _ : I => S) i)

/-- Elements which occur in `T` supported only in coordinate `i`. -/
def coordinateKernel
    {S I : Type*} [Group S] [DecidableEq I]
    (T : Subgroup (I → S)) (i : I) : Subgroup S :=
  T.comap (coordinateSingletonHom i)

/-- Transitivity of the coordinate action makes the coordinate projections of
an invariant subgroup uniform.  In particular, if one projection is all of
`S`, then every projection is all of `S`.  The automorphisms in `component`
allow for the usual coordinate-action model inside `Aut(S) wr Sym(I)`. -/
theorem coordinateProjections_eq_top_uniform
    {H S I : Type*} [Group S]
    (T : Subgroup (I → S))
    (sigma : H → Equiv.Perm I)
    (component : H → I → MulAut S)
    (hinvariant : ∀ h (f : I → S), f ∈ T →
      (fun i => component h i (f ((sigma h).symm i))) ∈ T)
    (htrans : ∀ i j : I, ∃ h : H, sigma h i = j)
    {i0 : I} (hi0 : coordinateProjection T i0 = ⊤) :
    ∀ i : I, coordinateProjection T i = ⊤ := by
  intro i
  apply top_unique
  intro y _
  obtain ⟨h, hh⟩ := htrans i0 i
  have hy0 : (component h i).symm y ∈ coordinateProjection T i0 := by
    rw [hi0]
    trivial
  rw [coordinateProjection, Subgroup.mem_map] at hy0
  obtain ⟨f, hf, hfi0⟩ := hy0
  change f i0 = (component h i).symm y at hfi0
  rw [coordinateProjection, Subgroup.mem_map]
  refine ⟨fun j => component h j (f ((sigma h).symm j)), hinvariant h f hf, ?_⟩
  change component h i (f ((sigma h).symm i)) = y
  have hh' : (sigma h).symm i = i0 := by
    apply (sigma h).injective
    simpa using hh.symm
  rw [hh', hfi0]
  simp

/-- Components contributed at a fixed coordinate by elements which stabilize
that coordinate. -/
def stabilizerComponentSet
    {H S I : Type*} [Group S]
    (sigma : H → Equiv.Perm I) (component : H → I → MulAut S)
    (i : I) : Set (MulAut S) :=
  {a | ∃ h : H, sigma h i = i ∧ component h i = a}

set_option maxHeartbeats 1000000 in
/-- If `X` is generated by the components of coordinate stabilizers together
with inner automorphisms, each coordinate projection of an invariant subgroup
has `X`-stable conjugacy class.  Finiteness is used only to turn forward
invariance under a component automorphism into equality. -/
theorem stable_coordinateProjection_of_component_generators
    {H S I : Type*} [Group S] [Finite S]
    (T : Subgroup (I → S))
    (sigma : H → Equiv.Perm I)
    (component : H → I → MulAut S)
    (hinvariant : ∀ h (f : I → S), f ∈ T →
      (fun i => component h i (f ((sigma h).symm i))) ∈ T)
    (X : Subgroup (MulAut S))
    (hXle : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet sigma component i ∪ Set.range MulAut.conj)) :
    ∀ i, StableSubgroupClass X (coordinateProjection T i) := by
  intro i
  have hgen : ∀ a ∈
      (stabilizerComponentSet sigma component i ∪ Set.range MulAut.conj),
      ∃ s : S, ∀ y : S, y ∈ coordinateProjection T i ↔
        s⁻¹ * a y * s ∈ coordinateProjection T i := by
    intro a ha
    rcases ha with ha | ha
    · obtain ⟨h, hfix, rfl⟩ := ha
      let W := coordinateProjection T i
      have hmap_le : W.map (component h i).toMonoidHom ≤ W := by
        intro y hy
        rw [Subgroup.mem_map] at hy
        obtain ⟨x, hx, rfl⟩ := hy
        change x ∈ coordinateProjection T i at hx
        rw [coordinateProjection, Subgroup.mem_map] at hx
        obtain ⟨f, hf, hfi⟩ := hx
        change f i = x at hfi
        change component h i x ∈ coordinateProjection T i
        rw [coordinateProjection, Subgroup.mem_map]
        refine ⟨fun j => component h j (f ((sigma h).symm j)),
          hinvariant h f hf, ?_⟩
        change component h i (f ((sigma h).symm i)) = component h i x
        have hfix' : (sigma h).symm i = i := by
          apply (sigma h).injective
          simpa using hfix.symm
        rw [hfix', hfi]
      have hmap : W.map (component h i).toMonoidHom = W := by
        apply Subgroup.eq_of_le_of_card_ge hmap_le
        have hcard : Nat.card W =
            Nat.card (W.map (component h i).toMonoidHom) :=
          Nat.card_congr ((component h i).subgroupMap W).toEquiv
        exact hcard.le
      refine ⟨1, ?_⟩
      intro y
      simp only [inv_one, one_mul, mul_one]
      change y ∈ W ↔ (component h i) y ∈ W
      constructor
      · intro hy
        have hy' : (component h i) y ∈
            W.map (component h i).toMonoidHom := ⟨y, hy, rfl⟩
        rwa [hmap] at hy'
      · intro hy
        have hy' : (component h i) y ∈
            W.map (component h i).toMonoidHom := by rwa [hmap]
        rw [Subgroup.mem_map_equiv] at hy'
        simpa using hy'
    · obtain ⟨s, rfl⟩ := ha
      refine ⟨s, ?_⟩
      intro y
      simp [mul_assoc]
  have hclosure := stableSubgroupClass_closure
    (coordinateProjection T i)
    (stabilizerComponentSet sigma component i ∪ Set.range MulAut.conj) hgen
  intro a ha
  exact hclosure a (hXle i ha)

/-- Goursat/saturation step from manuscript Lemma 3.3.

If `V` normally saturates every overgroup and `T ≤ S^I` contains the full
coordinate product `V^I`, then `T` is exactly the product of its coordinate
projections.  The proof constructs the coordinate kernel, proves it normal in
the corresponding projection, invokes saturation, and rebuilds an arbitrary
product element using commuting coordinate singletons. -/
theorem saturation_forces_coordinate_product
    {S I : Type*} [Group S] [Fintype I] [DecidableEq I]
    (V : Subgroup S) (hSat : NormallySaturating V)
    (T : Subgroup (I → S))
    (hVT : Subgroup.pi Set.univ (fun _ : I => V) ≤ T) :
    T = Subgroup.pi Set.univ (fun i : I => coordinateProjection T i) := by
  let W : I → Subgroup S := fun i => coordinateProjection T i
  let K : I → Subgroup S := fun i => coordinateKernel T i
  have hVK (i : I) : V ≤ K i := by
    intro y hy
    apply hVT
    apply (Subgroup.mem_pi Set.univ).2
    intro j _
    by_cases hji : j = i
    · subst j
      simpa [K, coordinateKernel, coordinateSingletonHom] using hy
    · simp [coordinateSingletonHom, hji]
  have hKW (i : I) : K i ≤ W i := by
    intro y hy
    change y ∈ coordinateProjection T i
    rw [coordinateProjection, Subgroup.mem_map]
    refine ⟨coordinateSingletonHom i y, hy, ?_⟩
    simp [coordinateSingletonHom]
  have hnormal (i : I) : ((K i).subgroupOf (W i)).Normal := by
    constructor
    intro n hn g
    have hnK : (n : S) ∈ K i := hn
    have hgW : (g : S) ∈ W i := g.property
    change (g : S) ∈ coordinateProjection T i at hgW
    rw [coordinateProjection, Subgroup.mem_map] at hgW
    obtain ⟨t, ht, hti⟩ := hgW
    change t i = (g : S) at hti
    have hnT : coordinateSingletonHom i (n : S) ∈ T := hnK
    have hcT : t * coordinateSingletonHom i (n : S) * t⁻¹ ∈ T :=
      T.mul_mem (T.mul_mem ht hnT) (T.inv_mem ht)
    change coordinateSingletonHom i ((g : S) * (n : S) * (g : S)⁻¹) ∈ T
    convert hcT using 1
    ext j
    by_cases hji : j = i
    · subst j
      simp [coordinateSingletonHom]
      rw [hti]
    · simp [coordinateSingletonHom, hji]
  have hKW_eq (i : I) : K i = W i := by
    have hVW : V ≤ W i := (hVK i).trans (hKW i)
    have hclosure := hSat (W i) hVW
    letI : ((K i).subgroupOf (W i)).Normal := hnormal i
    have hsub : Subgroup.normalClosure (V.subgroupOf (W i) : Set (W i)) ≤
        (K i).subgroupOf (W i) := by
      apply Subgroup.normalClosure_le_normal
      intro v hv
      exact hVK i hv
    rw [hclosure] at hsub
    apply le_antisymm (hKW i)
    intro w hw
    have hwtop : (⟨w, hw⟩ : W i) ∈ (⊤ : Subgroup (W i)) := trivial
    have hwK : (⟨w, hw⟩ : W i) ∈ (K i).subgroupOf (W i) := hsub hwtop
    exact hwK
  apply le_antisymm
  · intro f hf
    apply (Subgroup.mem_pi Set.univ).2
    intro i _
    rw [coordinateProjection, Subgroup.mem_map]
    exact ⟨f, hf, rfl⟩
  · intro f hf
    have hsingle (i : I) : coordinateSingletonHom i (f i) ∈ T := by
      have hfiW : f i ∈ W i :=
        (Subgroup.mem_pi Set.univ).mp hf i (Set.mem_univ i)
      have hfiK : f i ∈ K i := by rwa [hKW_eq i]
      exact hfiK
    let comm : (↑(Finset.univ : Finset I) : Set I).Pairwise
        (Function.onFun Commute (fun i => coordinateSingletonHom i (f i))) :=
      fun i _ j _ _ => Pi.mulSingle_apply_commute f i j
    have hp : Finset.univ.noncommProd
        (fun i => coordinateSingletonHom i (f i)) comm ∈ T :=
      Finset.noncommProd_induction Finset.univ
        (fun i => coordinateSingletonHom i (f i)) comm
        (fun x => x ∈ T) (fun _ _ => T.mul_mem) T.one_mem
        (fun i _ => hsingle i)
    have heq : Finset.univ.noncommProd
        (fun i => coordinateSingletonHom i (f i)) comm = f := by
      exact Finset.noncommProd_mulSingle f
    rwa [heq] at hp

/-- The exact direct-power intersection dichotomy underlying manuscript
Lemma 3.3.  Normal saturation first makes `T` a product of its projections;
the coordinate-closure generators make those projections `X`-stable; poset
maximality makes each projection `V` or `S`; and coordinate transitivity
prevents a mixture of the two cases. -/
theorem coordinate_intersection_eq_base_or_top
    {H S I : Type*} [Group S] [Finite S] [IsSimpleGroup S]
    [Fintype I] [DecidableEq I] [Nonempty I]
    (V : Subgroup S) (X : Subgroup (MulAut S))
    (T : Subgroup (I → S))
    (sigma : H → Equiv.Perm I)
    (component : H → I → MulAut S)
    (hinvariant : ∀ h (f : I → S), f ∈ T →
      (fun i => component h i (f ((sigma h).symm i))) ∈ T)
    (htrans : ∀ i j : I, ∃ h : H, sigma h i = j)
    (hXle : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet sigma component i ∪ Set.range MulAut.conj))
    (hVbot : V ≠ ⊥)
    (hVT : Subgroup.pi Set.univ (fun _ : I => V) ≤ T)
    (hSat : NormallySaturating V)
    (hmax : PosetMaximalStableSelfNormalizing X V) :
    T = Subgroup.pi Set.univ (fun _ : I => V) ∨ T = ⊤ := by
  have hstable := stable_coordinateProjection_of_component_generators
    T sigma component hinvariant X hXle
  have hVW (i : I) : V ≤ coordinateProjection T i := by
    intro y hy
    rw [coordinateProjection, Subgroup.mem_map]
    refine ⟨coordinateSingletonHom i y, ?_, ?_⟩
    · apply hVT
      apply (Subgroup.mem_pi Set.univ).2
      intro j _
      by_cases hji : j = i
      · subst j
        simpa [coordinateSingletonHom] using hy
      · simp [coordinateSingletonHom, hji]
    · simp [coordinateSingletonHom]
  have hor (i : I) : coordinateProjection T i = V ∨
      coordinateProjection T i = ⊤ :=
    stable_overgroup_eq_or_top X V (coordinateProjection T i)
      hVbot (hVW i) (hstable i) hmax
  have hprod := saturation_forces_coordinate_product V hSat T hVT
  by_cases htop : ∃ i : I, coordinateProjection T i = ⊤
  · right
    obtain ⟨i0, hi0⟩ := htop
    have hall := coordinateProjections_eq_top_uniform
      T sigma component hinvariant htrans hi0
    rw [hprod]
    apply top_unique
    intro f _
    apply (Subgroup.mem_pi Set.univ).2
    intro i _
    rw [hall i]
    trivial
  · left
    rw [hprod]
    congr 1
    funext i
    rcases hor i with hi | hi
    · exact hi
    · exact False.elim (htop ⟨i, hi⟩)

/-- Exact order of any subgroup supplementing a finite normal subgroup. -/
theorem card_subgroup_eq_card_quotient_mul_card_inf
    {G : Type*} [Group G] [Finite G]
    (N C : Subgroup G) [N.Normal]
    (hsup : C ⊔ N = (⊤ : Subgroup G)) :
    Nat.card C = Nat.card (G ⧸ N) * Nat.card ↥(C ⊓ N) := by
  let f : C →* G ⧸ N := (QuotientGroup.mk' N).comp C.subtype
  have hf : Function.Surjective f := by
    intro q
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective N q
    have hg : g ∈ C ⊔ N := by rw [hsup]; trivial
    change g ∈ (↑(C ⊔ N) : Set G) at hg
    rw [Subgroup.mul_normal] at hg
    obtain ⟨c, hc, n, hn, rfl⟩ := hg
    refine ⟨⟨c, hc⟩, ?_⟩
    change (c : G ⧸ N) = ((c * n : G) : G ⧸ N)
    rw [QuotientGroup.mk_mul, (QuotientGroup.eq_one_iff n).mpr hn, mul_one]
  have hker : f.ker = N.subgroupOf C := by
    calc
      f.ker = N.comap C.subtype := by
        change ((QuotientGroup.mk' N).comp C.subtype).ker = N.comap C.subtype
        rw [← MonoidHom.comap_ker, QuotientGroup.ker_mk']
      _ = N.subgroupOf C := Subgroup.comap_subtype N C
  have hkerCard : Nat.card f.ker = Nat.card ↥(C ⊓ N) := by
    rw [hker]
    have hle : C ⊓ N ≤ C := inf_le_left
    have heq : (C ⊓ N).subgroupOf C = N.subgroupOf C := by
      ext c
      simp
    rw [← heq]
    exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe hle).toEquiv
  have hrange : f.range = ⊤ := MonoidHom.range_eq_top.mpr hf
  calc
    Nat.card C = Nat.card f.ker * f.ker.index := f.ker.card_mul_index.symm
    _ = Nat.card f.ker * Nat.card f.range := by rw [Subgroup.index_ker]
    _ = Nat.card ↥(C ⊓ N) * Nat.card (G ⧸ N) := by
      rw [hkerCard, hrange, Subgroup.card_top]
    _ = Nat.card (G ⧸ N) * Nat.card ↥(C ⊓ N) := Nat.mul_comm _ _

/-- Final lattice/cardinality step of manuscript Lemma 3.3.

Once every overgroup `H ≥ B` has intersection `A` with `N` or contains all of
`N`, a proper supplement `B` is a coatom.  Thus the remaining maximality
obligation is precisely the intersection dichotomy produced by the ambient
coordinate action and the stable-class poset. -/
theorem isCoatom_of_supplement_intersection_dichotomy
    {G : Type*} [Group G] [Finite G]
    (N B A : Subgroup G) [N.Normal]
    (hBne : B ≠ ⊤)
    (hsup : B ⊔ N = (⊤ : Subgroup G))
    (hinf : B ⊓ N = A)
    (hdichotomy : ∀ H : Subgroup G, B ≤ H → H ⊓ N = A ∨ N ≤ H) :
    IsCoatom B := by
  rw [isCoatom_iff_ge_of_le]
  refine ⟨hBne, ?_⟩
  intro H hHne hBH
  rcases hdichotomy H hBH with hHinf | hNH
  · have hHsup : H ⊔ N = (⊤ : Subgroup G) := by
      apply top_unique
      rw [← hsup]
      exact sup_le_sup hBH le_rfl
    have hcardB := card_subgroup_eq_card_quotient_mul_card_inf N B hsup
    have hcardH := card_subgroup_eq_card_quotient_mul_card_inf N H hHsup
    rw [hinf] at hcardB
    rw [hHinf] at hcardH
    exact (Subgroup.eq_of_le_of_card_ge hBH (by omega)).ge
  · exfalso
    apply hHne
    apply top_unique
    rw [← hsup]
    exact sup_le hBH hNH


theorem coordinateClosure_le_of_supplement
    {G S I : Type*} [Group G] [Group S]
    (N H : Subgroup G) [N.Normal]
    (hsup : H ⊔ N = (⊤ : Subgroup G))
    (sigma : G →* Equiv.Perm I)
    (component : G → I → MulAut S)
    (hNperm : ∀ n : N, sigma n = 1)
    (hcomp_mul : ∀ g h i, component (g * h) i =
      component g i * component h ((sigma g).symm i))
    (hNcomp : ∀ n : N, ∀ i, ∃ s : S, component n i = MulAut.conj s)
    (X : Subgroup (MulAut S))
    (hXgen : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet (fun g : G => sigma g) component i ∪
        Set.range MulAut.conj)) :
    ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet (fun h : H => sigma h)
        (fun h i => component h i) i ∪ Set.range MulAut.conj) := by
  intro i
  let YH : Set (MulAut S) :=
    stabilizerComponentSet (fun h : H => sigma h)
      (fun h i => component h i) i ∪ Set.range MulAut.conj
  apply (hXgen i).trans
  rw [Subgroup.closure_le]
  intro a ha
  rcases ha with ha | ha
  · obtain ⟨g, hgfix, rfl⟩ := ha
    have hgmem : g ∈ H ⊔ N := by rw [hsup]; trivial
    change g ∈ (↑(H ⊔ N) : Set G) at hgmem
    rw [Subgroup.mul_normal] at hgmem
    obtain ⟨h, hhH, n, hnN, hgn⟩ := hgmem
    let hH : H := ⟨h, hhH⟩
    let nN : N := ⟨n, hnN⟩
    have hsigman : sigma n = 1 := hNperm nN
    have hsigmah : sigma h = sigma g := by
      rw [← hgn, map_mul, hsigman, mul_one]
    have hhfix : sigma h i = i := by rw [hsigmah, hgfix]
    have hhgen : component h i ∈ YH := by
      left
      exact ⟨hH, hhfix, rfl⟩
    obtain ⟨s, hs⟩ := hNcomp nN i
    have hngen : component n i ∈ YH := by
      right
      exact ⟨s, hs.symm⟩
    have hsource : (sigma h).symm i = i := by
      apply (sigma h).injective
      simpa using hhfix.symm
    rw [← hgn, hcomp_mul, hsource]
    exact Subgroup.mul_mem _
      (Subgroup.subset_closure hhgen) (Subgroup.subset_closure hngen)
  · exact Subgroup.subset_closure (Or.inr ha)

/-- Transport `H ∩ N` into direct-power coordinates. -/
def coordinateIntersection
    {G S I : Type*} [Group G] [Group S]
    (H N : Subgroup G) (coord : N ≃* (I → S)) : Subgroup (I → S) :=
  ((H ⊓ N).subgroupOf N).map coord.toMonoidHom

theorem mem_coordinateIntersection
    {G S I : Type*} [Group G] [Group S]
    (H N : Subgroup G) (coord : N ≃* (I → S)) (f : I → S) :
    f ∈ coordinateIntersection H N coord ↔ ((coord.symm f : N) : G) ∈ H := by
  rw [coordinateIntersection, Subgroup.mem_map_equiv, Subgroup.mem_subgroupOf]
  simp

theorem coordinateIntersection_invariant
    {G S I : Type*} [Group G] [Group S]
    (N H : Subgroup G) [N.Normal]
    (coord : N ≃* (I → S))
    (sigma : G →* Equiv.Perm I)
    (component : G → I → MulAut S)
    (haction : ∀ g (z : N) i,
      coord (MulAut.conjNormal g z) i =
        component g i (coord z ((sigma g).symm i))) :
    ∀ h : H, ∀ f ∈ coordinateIntersection H N coord,
      (fun i => component h i (f ((sigma h).symm i))) ∈
        coordinateIntersection H N coord := by
  intro h f hf
  rw [mem_coordinateIntersection] at hf ⊢
  let z : N := coord.symm f
  let q : N := MulAut.conjNormal (h : G) z
  have hqH : (q : G) ∈ H := by
    change (h : G) * (z : G) * (h : G)⁻¹ ∈ H
    exact H.mul_mem (H.mul_mem h.property hf) (H.inv_mem h.property)
  have heq : coord q = fun i => component h i (f ((sigma h).symm i)) := by
    funext i
    rw [haction]
    simp [z]
  rw [← heq]
  simpa [q] using hqH

theorem supplement_action_transitive
    {G I : Type*} [Group G]
    (N H : Subgroup G) [N.Normal]
    (hsup : H ⊔ N = (⊤ : Subgroup G))
    (sigma : G →* Equiv.Perm I)
    (hNperm : ∀ n : N, sigma n = 1)
    (htransG : ∀ i j : I, ∃ g : G, sigma g i = j) :
    ∀ i j : I, ∃ h : H, sigma h i = j := by
  intro i j
  obtain ⟨g, hgij⟩ := htransG i j
  have hgmem : g ∈ H ⊔ N := by rw [hsup]; trivial
  change g ∈ (↑(H ⊔ N) : Set G) at hgmem
  rw [Subgroup.mul_normal] at hgmem
  obtain ⟨h, hhH, n, hnN, hgn⟩ := hgmem
  let nN : N := ⟨n, hnN⟩
  have hsigman : sigma n = 1 := hNperm nN
  have hsigmah : sigma h = sigma g := by
    rw [← hgn, map_mul, hsigman, mul_one]
  exact ⟨⟨h, hhH⟩, by simpa [hsigmah] using hgij⟩

theorem ambient_supplement_intersection_dichotomy
    {G S I : Type*} [Group G] [Group S] [Finite S] [IsSimpleGroup S]
    [Fintype I] [DecidableEq I] [Nonempty I]
    (N A B : Subgroup G) [N.Normal]
    (V : Subgroup S) (X : Subgroup (MulAut S))
    (coord : N ≃* (I → S))
    (sigma : G →* Equiv.Perm I)
    (component : G → I → MulAut S)
    (hAN : A ≤ N)
    (hA : ∀ z : N, (z : G) ∈ A ↔ ∀ i, coord z i ∈ V)
    (hAB : A ≤ B)
    (hBN : B ⊔ N = (⊤ : Subgroup G))
    (hNperm : ∀ n : N, sigma n = 1)
    (hcomp_mul : ∀ g h i, component (g * h) i =
      component g i * component h ((sigma g).symm i))
    (hNcomp : ∀ n : N, ∀ i, ∃ s : S, component n i = MulAut.conj s)
    (hXgen : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet (fun g : G => sigma g) component i ∪
        Set.range MulAut.conj))
    (haction : ∀ g (z : N) i,
      coord (MulAut.conjNormal g z) i =
        component g i (coord z ((sigma g).symm i)))
    (htransG : ∀ i j : I, ∃ g : G, sigma g i = j)
    (hVbot : V ≠ ⊥)
    (hSat : NormallySaturating V)
    (hmax : PosetMaximalStableSelfNormalizing X V) :
    ∀ H : Subgroup G, B ≤ H → H ⊓ N = A ∨ N ≤ H := by
  intro H hBH
  have hHsup : H ⊔ N = (⊤ : Subgroup G) := by
    apply top_unique
    rw [← hBN]
    exact sup_le_sup hBH le_rfl
  let T : Subgroup (I → S) := coordinateIntersection H N coord
  let sigmaH : H → Equiv.Perm I := fun h => sigma h
  let componentH : H → I → MulAut S := fun h i => component h i
  have hinvariant : ∀ h : H, ∀ f ∈ T,
      (fun i => componentH h i (f ((sigmaH h).symm i))) ∈ T := by
    exact coordinateIntersection_invariant N H coord sigma component haction
  have htrans : ∀ i j : I, ∃ h : H, sigmaH h i = j := by
    exact supplement_action_transitive N H hHsup sigma hNperm htransG
  have hXle : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet sigmaH componentH i ∪ Set.range MulAut.conj) := by
    exact coordinateClosure_le_of_supplement N H hHsup sigma component
      hNperm hcomp_mul hNcomp X hXgen
  have hVT : Subgroup.pi Set.univ (fun _ : I => V) ≤ T := by
    intro f hf
    rw [mem_coordinateIntersection]
    apply hBH
    apply hAB
    apply (hA (coord.symm f)).2
    intro i
    simpa using (Subgroup.mem_pi Set.univ).mp hf i (Set.mem_univ i)
  rcases coordinate_intersection_eq_base_or_top V X T sigmaH componentH
      hinvariant htrans hXle hVbot hVT hSat hmax with hTbase | hTtop
  · left
    have hmapA : (A.subgroupOf N).map coord.toMonoidHom =
        Subgroup.pi Set.univ (fun _ : I => V) := by
      ext f
      rw [Subgroup.mem_map_equiv, Subgroup.mem_subgroupOf, hA]
      simp [Subgroup.mem_pi]
    have hsubN : (H ⊓ N).subgroupOf N = A.subgroupOf N := by
      apply (Subgroup.map_injective (f := coord.toMonoidHom) coord.injective)
      change T = (A.subgroupOf N).map coord.toMonoidHom
      rw [hTbase, hmapA]
    have hi := Subgroup.subgroupOf_inj.mp hsubN
    simpa [inf_eq_left.mpr hAN] using hi
  · right
    intro n hn
    let nN : N := ⟨n, hn⟩
    have hf : coord nN ∈ T := by rw [hTtop]; trivial
    simpa [nN] using (mem_coordinateIntersection H N coord (coord nN)).mp hf

theorem supplement_ne_top_of_proper_coordinate_base
    {G S I : Type*} [Group G] [Group S]
    [DecidableEq I] [Nonempty I]
    (N A B : Subgroup G)
    (V : Subgroup S) (coord : N ≃* (I → S))
    (hA : ∀ z : N, (z : G) ∈ A ↔ ∀ i, coord z i ∈ V)
    (hinf : B ⊓ N = A)
    (hVtop : V ≠ ⊤) : B ≠ ⊤ := by
  intro hBtop
  have hANeq : A = N := by
    rw [← hinf, hBtop, top_inf_eq]
  apply hVtop
  apply top_unique
  intro y _
  let i0 : I := Classical.choice (inferInstance : Nonempty I)
  let f : I → S := Function.update (fun _ => 1) i0 y
  let z : N := coord.symm f
  have hzA : (z : G) ∈ A := by rw [hANeq]; exact z.property
  have hzi := (hA z).mp hzA i0
  simpa [z, f] using hzi

/-- Exact ambient maximality conclusion of manuscript Lemma 3.3, conditional
on the normalized coordinate-action data and the intersection/supplement
identities supplied by the existence lemma. -/
theorem coordinate_product_normalizer_isCoatom
    {G S I : Type*} [Group G] [Finite G]
    [Group S] [Finite S] [IsSimpleGroup S]
    [Fintype I] [DecidableEq I] [Nonempty I]
    (N A : Subgroup G) [N.Normal]
    (V : Subgroup S) (X : Subgroup (MulAut S))
    (coord : N ≃* (I → S))
    (sigma : G →* Equiv.Perm I)
    (component : G → I → MulAut S)
    (hAN : A ≤ N)
    (hA : ∀ z : N, (z : G) ∈ A ↔ ∀ i, coord z i ∈ V)
    (hinf : Subgroup.normalizer (A : Set G) ⊓ N = A)
    (hsup : Subgroup.normalizer (A : Set G) ⊔ N = (⊤ : Subgroup G))
    (hNperm : ∀ n : N, sigma n = 1)
    (hcomp_mul : ∀ g h i, component (g * h) i =
      component g i * component h ((sigma g).symm i))
    (hNcomp : ∀ n : N, ∀ i, ∃ s : S, component n i = MulAut.conj s)
    (hXgen : ∀ i, X ≤ Subgroup.closure
      (stabilizerComponentSet (fun g : G => sigma g) component i ∪
        Set.range MulAut.conj))
    (haction : ∀ g (z : N) i,
      coord (MulAut.conjNormal g z) i =
        component g i (coord z ((sigma g).symm i)))
    (htransG : ∀ i j : I, ∃ g : G, sigma g i = j)
    (hVbot : V ≠ ⊥)
    (hVtop : V ≠ ⊤)
    (hSat : NormallySaturating V)
    (hmax : PosetMaximalStableSelfNormalizing X V) :
    IsCoatom (Subgroup.normalizer (A : Set G)) := by
  let B : Subgroup G := Subgroup.normalizer (A : Set G)
  have hAB : A ≤ B := fun _ ha => Subgroup.le_normalizer ha
  have hBne : B ≠ ⊤ :=
    supplement_ne_top_of_proper_coordinate_base N A B V coord hA hinf hVtop
  have hdichotomy : ∀ H : Subgroup G, B ≤ H → H ⊓ N = A ∨ N ≤ H :=
    ambient_supplement_intersection_dichotomy N A B V X coord sigma
      component hAN hA hAB hsup hNperm hcomp_mul hNcomp hXgen haction
      htransG hVbot hSat hmax
  exact isCoatom_of_supplement_intersection_dichotomy
    N B A hBne hsup hinf hdichotomy
end Kourovka1034
