#!/usr/bin/env python3
# Coverage cross-check for the |S| < 500000 base theorem.
#
# Verifies that every non-abelian simple group S with |S| < 500000
# (canonical list: simple_groups_below_500000.txt, generated by GAP's
# SimpleGroupsIterator(60, 499999) — 47 groups) is covered by an all-k
# exclusion certificate:
#   - "==> NAME^k EXCLUDED FOR ALL k >= 2 AND ALL X" in sweep J, J2 or J4, or
#   - a per-X novelty exclusion in sweep K (the four exceptional families
#     L3(2), A6, L2(11), L3(4), each of whose X-lines must read
#     "ALL k >= 2 EXCLUDED").
# Exits nonzero and names the gap if any group is uncovered.

import re
import sys
from pathlib import Path

COMPUTATIONS = Path(__file__).resolve().parents[1]
CERTIFICATES = COMPUTATIONS / 'certificates'
DATA = COMPUTATIONS / 'data'

COVERED_LOGS = [
    CERTIFICATES / 'sweepJ_divisibility.log',
    CERTIFICATES / 'sweepJ2_tail.log',
    CERTIFICATES / 'sweepJ4_patch.log',
]
K_LOG = CERTIFICATES / 'sweepK_novelty.log'
CANONICAL = DATA / 'simple_groups_below_500000.txt'

ALIAS = {
    'A5': 'A5', 'PSL(2,7)': 'L3_2', 'PSL(3,2)': 'L3_2', 'A6': 'A6',
    'PSL(2,8)': 'L2_8', 'PSL(2,11)': 'L2_11', 'PSL(2,13)': 'L2_13',
    'PSL(2,17)': 'L2_17', 'A7': 'A7', 'PSL(2,19)': 'L2_19',
    'PSL(2,16)': 'L2_16', 'PSL(3,3)': 'L3_3', 'PSU(3,3)': 'U3_3',
    'PSL(2,23)': 'L2_23', 'PSL(2,25)': 'L2_25', 'M11': 'M11',
    'PSL(2,27)': 'L2_27', 'PSL(2,29)': 'L2_29', 'PSL(2,31)': 'L2_31',
    'A8': 'A8', 'PSL(4,2)': 'A8', 'PSL(3,4)': 'L3_4', 'PSL(2,37)': 'L2_37',
    'PSp(4,3)': 'Sp43', 'PSU(4,2)': 'Sp43', 'O(5,3)': 'Sp43',
    'Sz(8)': 'Sz8', 'PSL(2,32)': 'L2_32', 'PSL(2,41)': 'L2_41',
    'PSL(2,43)': 'L2_43', 'PSL(2,47)': 'L2_47', 'PSL(2,49)': 'L2_49',
    'PSU(3,4)': 'U3_4', 'PSL(2,53)': 'L2_53', 'M12': 'M12',
    'PSL(2,59)': 'L2_59', 'PSL(2,61)': 'L2_61', 'PSU(3,5)': 'U3_5',
    'PSL(2,67)': 'L2_67', 'J1': 'J1', 'PSL(2,71)': 'L2_71', 'A9': 'A9',
    'PSL(2,73)': 'L2_73', 'PSL(2,79)': 'L2_79', 'PSL(2,64)': 'L2_64',
    'PSL(2,81)': 'L2_81', 'PSL(2,83)': 'L2_83', 'PSL(2,89)': 'L2_89',
    'PSL(3,5)': 'L3_5', 'M22': 'M22', 'PSL(2,97)': 'L2_97',
}


def main():
    covered = set()
    for f in COVERED_LOGS:
        txt = f.read_text()
        covered |= set(re.findall(r'==> (\S+)\^k EXCLUDED FOR ALL', txt))

    # sweep K: every X-line of each family section must be an all-k exclusion
    ktxt = K_LOG.read_text()
    kcov = set()
    sections = re.split(r'(?=### )', ktxt)
    for sec in sections:
        m = re.match(r'### (\S+):', sec)
        if not m:
            continue
        xlines = re.findall(r'X/Inn.*', sec)
        allk = re.findall(r'ALL k >= 2 EXCLUDED', sec)
        if xlines and len(allk) >= len(xlines):
            kcov.add(m.group(1))

    total, missing = 0, []
    for line in CANONICAL.read_text().splitlines():
        parts = line.split(None, 1)
        if len(parts) != 2 or parts[0] == 'TOTAL':
            continue
        size, name = parts[0], parts[1].strip()
        total += 1
        key = ALIAS.get(name)
        if key is None:
            missing.append((size, name, 'UNMAPPED'))
        elif key not in covered and key not in kcov:
            missing.append((size, name, key))

    print(f'canonical groups checked: {total}')
    print(f'all-k certified (J/J2/J4): {len(covered)}')
    print(f'novelty-certified (K): {sorted(kcov)}')
    if missing:
        print('GAPS:', missing)
        sys.exit(1)
    print('COVERAGE COMPLETE: every simple S, |S| < 500000, is certified '
          'excluded as a socle S^k for all k >= 2 and all X.')


if __name__ == '__main__':
    main()
