#!/usr/bin/env python3
# Coverage cross-check for the 500000 <= |S| <= 10500000 extension.
#
# Canonical list: simple_groups_5e5_to_1.05e7.txt, generated by GAP's
# SimpleGroupsIterator(500000, 10500000) (gen_biglist.g) -- 51 groups,
# with pairwise distinct orders in this window (no B_n/C_n or A_8/L3(4)
# order coincidences occur here; asserted below).
#
# Each canonical group must be matched, BY ORDER, to a sweep J3 entry
# ("### NAME: |S| = ORDER = ...") that either
#   - carries the line "==> NAME^k EXCLUDED FOR ALL k >= 2 AND ALL X", or
#   - is one of the two documented survivors, O(5,4) and PSL(5,2), whose
#     all-X novelty closures are certified in sweeps K3 and K4 (their
#     final "ALL k >= 2 EXCLUDED FOR ALL X" lines are re-checked here).
import re, sys

canon = {}
for line in open("simple_groups_5e5_to_1.05e7.txt"):
    order, name = line.split()
    order = int(order)
    assert order not in canon, f"order collision at {order}"
    canon[order] = name
assert len(canon) == 51, len(canon)

log = open("sweepJ3_bigrange.log").read()
# J3 entries: capture name and order; entries may wrap lines.
entries = {}
for m in re.finditer(r"^### ([^:]+): \|S\| = (\d+)", log, re.M):
    entries[int(m.group(2))] = m.group(1)

problems = []
survivors_expected = {"O(5,4)", "PSL(5,2)"}
survivors_seen = set()
for order, name in sorted(canon.items()):
    if order not in entries:
        problems.append(f"MISSING from sweep J3: {name} (order {order})")
        continue
    j3name = entries[order]
    if f"==> {j3name}^k EXCLUDED FOR ALL k >= 2 AND ALL X" in log:
        continue
    if f"==> {j3name} SURVIVES" in log and j3name in survivors_expected:
        survivors_seen.add(j3name)
        continue
    problems.append(f"NO all-X certificate in J3 for {j3name} (order {order})")

if survivors_seen:
    k3 = open("sweepK3_bigsurvivors.log").read()
    k4 = open("sweepK4_L52.log").read()
    if "O(5,4)" in survivors_seen and \
       "O(5,4): ALL k >= 2 EXCLUDED FOR ALL X (novelty pair certified)." not in k3:
        problems.append("O(5,4) survivor not closed in sweep K3")
    if "PSL(5,2)" in survivors_seen and \
       "L5_2: ALL k >= 2 EXCLUDED FOR ALL X (novelty pair certified)." not in k4:
        problems.append("PSL(5,2) survivor not closed in sweep K4")

print(f"canonical groups in [5e5, 1.05e7]: {len(canon)}")
print(f"matched J3 entries: {sum(1 for o in canon if o in entries)}")
print(f"J3 survivors (closed by K3/K4): {sorted(survivors_seen)}")
for p in problems:
    print("PROBLEM:", p)
print("COVERAGE (big range) OK." if not problems else "COVERAGE HAS GAPS.")
sys.exit(1 if problems else 0)
