#!/usr/bin/env python3
"""Second, manifest-independent universal arithmetic implementation.

This file intentionally does **not** read FAMILY-ARITHMETIC-MANIFEST.json,
the primary sweep, or any generated certificate.  It independently encodes
the 34 branches of Theorems 6.1--6.6 in a compact symbolic representation and
checks every rank/field-degree inequality, group-factor occurrence, outer
factor, exceptional equation, and substitute valuation.  The finite sweep is
therefore regression evidence; this program is an unbounded symbolic proof
check layered on the published order-formula assumptions.

Published order formulas and Zsigmondy's theorem remain external assumptions;
this program checks the deductions made from those exact cited inputs.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import gcd, isqrt, prod
import sys


@dataclass(frozen=True)
class Lin:
    """Coefficient a*n+b, with the common positive field degree suppressed."""
    a: int
    b: int

    def at(self, n: int) -> int:
        return self.a * n + self.b

    def twice(self) -> "Lin":
        return Lin(2 * self.a, 2 * self.b)


@dataclass(frozen=True)
class PrimitiveCase:
    key: str
    # n_kind is none/fixed/variable.  n0 is 0, the fixed rank, or min rank.
    n_kind: str
    n0: int
    n_parity: str
    f0: int
    f_parity: str
    characteristic_two_allowed: bool
    exponent: Lin
    group_kind: str
    group_q_exponent: Lin
    # One complete upper-bound tuple for each selected subgroup (four entries
    # for 2E6, where any two of the four parabolic classes may be selected).
    selected: tuple[tuple[Lin, ...], ...]
    selected_constants: tuple[tuple[int, ...], ...]
    outer_kind: str
    outer_constant: int
    diagonal: tuple[Lin, ...]
    exception_points: tuple[tuple[int | None, int], ...]
    central: tuple[Lin, ...] = ()


def L(a: int, b: int) -> Lin:
    return Lin(a, b)


# Independent transcription of the manuscript.  These values are not loaded
# from, generated by, or compared through the JSON branch manifest.
CASES = (
    PrimitiveCase("AR-PSL2-EVEN", "none", 0, "any", 3, "any", True,
                  L(0, 2), "plus", L(0, 1), ((L(0, 1),), (L(0, 1),)),
                  ((), (2,)), "factor", 1, (), ((None, 3),)),
    PrimitiveCase("AR-C-HIGHRANK", "variable", 3, "any", 1, "any", True,
                  L(2, 0), "minus", L(2, 0), ((L(2, -2),), (L(2, -4), L(0, 2))),
                  ((), ()), "size", 4, (), ((3, 1),)),
    PrimitiveCase("AR-B-HIGHRANK", "variable", 3, "any", 1, "any", False,
                  L(2, 0), "minus", L(2, 0), ((L(2, -2),), (L(2, -4), L(0, 2))),
                  ((), ()), "size", 4, (), ()),
    PrimitiveCase("AR-C2-ODD", "fixed", 2, "any", 1, "any", False,
                  L(0, 4), "minus", L(0, 4), ((L(0, 2),), (L(0, 2),)),
                  ((), ()), "size", 4, (), ()),
    PrimitiveCase("AR-G2-NOGRAPH", "fixed", 2, "any", 1, "any", True,
                  L(0, 6), "minus", L(0, 6), ((L(0, 2),), (L(0, 2),)),
                  ((), ()), "size", 4, (), ((2, 1),)),
    PrimitiveCase("AR-F4-NOGRAPH", "fixed", 4, "any", 1, "any", False,
                  L(0, 12), "minus", L(0, 12), ((L(0, 6),), (L(0, 6),)),
                  ((), ()), "size", 4, (), ()),
    PrimitiveCase("AR-E7", "fixed", 7, "any", 1, "any", True,
                  L(0, 18), "minus", L(0, 18), ((L(0, 12),), (L(0, 12),)),
                  ((), ()), "size", 4, (), ()),
    PrimitiveCase("AR-E8", "fixed", 8, "any", 1, "any", True,
                  L(0, 30), "minus", L(0, 30), ((L(0, 18),), (L(0, 18),)),
                  ((), ()), "size", 4, (), ()),
    PrimitiveCase("AR-PSU-ODD", "variable", 5, "odd", 1, "any", True,
                  L(2, 0), "plus", L(1, 0),
                  ((L(0, 2), L(2, -4)), (L(0, 4), L(2, -8))),
                  ((), ()), "factor", 3, (L(0, 2),), ()),
    PrimitiveCase("AR-PSU-EVEN", "variable", 4, "even", 1, "any", True,
                  L(2, -2), "plus", L(1, -1),
                  ((L(0, 4), L(2, -6), L(1, -2)),
                   (L(0, 4), L(2, -6), L(1, -2))),
                  ((), ()), "factor", 3, (L(0, 2),), ((4, 1),)),
    PrimitiveCase("AR-2D", "variable", 4, "any", 1, "any", True,
                  L(2, 0), "plus", L(1, 0),
                  ((L(0, 1), L(2, -2)), (L(0, 2), L(2, -4))),
                  ((), ()), "factor", 12, (), ()),
    PrimitiveCase("AR-3D4", "fixed", 4, "any", 1, "any", True,
                  L(0, 12), "cyclotomic", L(0, 12),
                  ((L(0, 6), L(0, 1)), (L(0, 2), L(0, 3))),
                  ((), ()), "factor", 3, (), ()),
    PrimitiveCase("AR-2E6", "fixed", 6, "any", 1, "any", True,
                  L(0, 18), "plus", L(0, 9),
                  ((L(0, 10),), (L(0, 6),), (L(0, 8),), (L(0, 4),)),
                  ((), (), (), ()), "factor", 3, (L(0, 2),), ()),
    PrimitiveCase("AR-2F4", "fixed", 4, "any", 3, "odd", True,
                  L(0, 12), "plus", L(0, 6),
                  ((L(0, 4), L(0, 1)), (L(0, 2), L(0, 1))),
                  ((), ()), "factor", 3, (), ()),
    PrimitiveCase("AR-PSU3", "fixed", 3, "any", 1, "any", True,
                  L(0, 6), "plus", L(0, 3), ((L(0, 2),), (L(0, 2),)),
                  ((), ()), "factor", 2, (L(0, 2),), ((3, 1),)),
    PrimitiveCase("AR-SUZUKI", "fixed", 2, "any", 3, "odd", True,
                  L(0, 4), "plus", L(0, 2), ((L(0, 1),), (L(0, 1),)),
                  ((), (2,)), "factor", 1, (), ()),
    PrimitiveCase("AR-SMALL-REE", "fixed", 2, "any", 3, "odd", False,
                  L(0, 6), "plus", L(0, 3), ((L(0, 1),), (L(0, 2),)),
                  ((), ()), "factor", 1, (), ()),
    PrimitiveCase("AR-PSL-TRIVIAL", "variable", 3, "any", 1, "any", True,
                  L(1, 0), "minus", L(1, 0),
                  ((L(1, -1),), (L(0, 2), L(1, -2))),
                  ((), ()), "factor", 2, (L(0, 1),), ((3, 2), (6, 1)),
                  central=(L(0, 1),)),
    PrimitiveCase("AR-DPLUS", "variable", 4, "any", 1, "any", True,
                  L(2, -2), "minus", L(2, -2),
                  ((L(1, -1), L(2, -4)), (L(0, 2), L(1, -2), L(2, -6))),
                  ((), ()), "factor", 24, (), ((4, 1),)),
    PrimitiveCase("AR-SP4-TRIVIAL", "fixed", 2, "any", 2, "any", True,
                  L(0, 4), "plus", L(0, 2), ((L(0, 2),), (L(0, 2),)),
                  ((), ()), "factor", 1, (), ()),
    PrimitiveCase("AR-F4-TRIVIAL", "fixed", 4, "any", 1, "any", True,
                  L(0, 12), "minus", L(0, 12), ((L(0, 6),), (L(0, 6),)),
                  ((), ()), "factor", 1, (), ()),
    PrimitiveCase("AR-G2-TRIVIAL", "fixed", 2, "any", 1, "any", False,
                  L(0, 6), "minus", L(0, 6), ((L(0, 2),), (L(0, 2),)),
                  ((), ()), "factor", 1, (), ()),
    PrimitiveCase("AR-PSL3-GRAPH", "fixed", 3, "any", 1, "any", True,
                  L(0, 3), "minus", L(0, 3), ((L(0, 1),), (L(0, 1),)),
                  ((), (6,)), "factor", 2, (L(0, 1),), ((3, 2),),
                  central=(L(0, 1),)),
    PrimitiveCase("AR-PSL4-GRAPH", "fixed", 4, "any", 1, "any", True,
                  L(0, 4), "minus", L(0, 4), ((L(0, 2),), (L(0, 2), L(0, 1))),
                  ((), ()), "factor", 2, (L(0, 1),), (),
                  central=(L(0, 1),)),
    PrimitiveCase("AR-PSLN-GRAPH", "variable", 5, "any", 1, "any", True,
                  L(1, 0), "minus", L(1, 0),
                  ((L(1, -2), L(0, 1)), (L(0, 2), L(1, -4), L(0, 1))),
                  ((), ()), "factor", 2, (L(0, 1),), ((6, 1),),
                  central=(L(0, 1),)),
    PrimitiveCase("AR-D4-TRIALITY", "fixed", 4, "any", 1, "any", True,
                  L(0, 6), "minus", L(0, 6), ((L(0, 2),), (L(0, 2), L(0, 1))),
                  ((), ()), "factor", 24, (), ((4, 1),)),
    PrimitiveCase("AR-E6", "fixed", 6, "any", 1, "any", True,
                  L(0, 12), "minus", L(0, 12), ((L(0, 6),), (L(0, 3),)),
                  ((), ()), "factor", 2, (L(0, 1),), (),
                  central=(L(0, 1),)),
    PrimitiveCase("AR-SP4-GRAPH-ODD", "fixed", 2, "any", 3, "odd", True,
                  L(0, 2), "plus", L(0, 1), ((L(0, 1),), (L(0, 1),)),
                  ((), ()), "factor", 2, (), ((2, 3),)),
    PrimitiveCase("AR-SP4-GRAPH-EVEN", "fixed", 2, "any", 2, "even", True,
                  L(0, 4), "plus", L(0, 2), ((L(0, 1),), (L(0, 2), L(0, 1))),
                  ((), ()), "factor", 2, (), ()),
    PrimitiveCase("AR-F4-GRAPH", "fixed", 4, "any", 1, "any", True,
                  L(0, 12), "minus", L(0, 12),
                  ((L(0, 4), L(0, 1)), (L(0, 2), L(0, 1))),
                  ((), ()), "factor", 2, (), ()),
    PrimitiveCase("AR-G2-GRAPH-ODD", "fixed", 2, "any", 1, "odd", False,
                  L(0, 3), "minus", L(0, 3), ((L(0, 1),), (L(0, 1),)),
                  ((), ()), "factor", 2, (), ()),
    PrimitiveCase("AR-G2-GRAPH-EVEN", "fixed", 2, "any", 2, "even", False,
                  L(0, 6), "plus", L(0, 3), ((L(0, 1),), (L(0, 3), L(0, 1))),
                  ((), ()), "factor", 2, (), ()),
)


EXPECTED_KEYS = (
    "AR-PSL2-ODD", "AR-PSL2-EVEN", "AR-ALTERNATING",
    "AR-C-HIGHRANK", "AR-B-HIGHRANK", "AR-C2-ODD", "AR-G2-NOGRAPH",
    "AR-F4-NOGRAPH", "AR-E7", "AR-E8", "AR-PSU-ODD", "AR-PSU-EVEN",
    "AR-2D", "AR-3D4", "AR-2E6", "AR-2F4", "AR-PSU3", "AR-SUZUKI",
    "AR-SMALL-REE", "AR-PSL-TRIVIAL", "AR-DPLUS", "AR-SP4-TRIVIAL",
    "AR-F4-TRIVIAL", "AR-G2-TRIVIAL", "AR-PSL3-GRAPH",
    "AR-PSL4-GRAPH", "AR-PSLN-GRAPH", "AR-D4-TRIALITY", "AR-E6",
    "AR-SP4-GRAPH-ODD", "AR-SP4-GRAPH-EVEN", "AR-F4-GRAPH",
    "AR-G2-GRAPH-ODD", "AR-G2-GRAPH-EVEN",
)

# Exact direct-branch data, independently transcribed rather than loaded from
# the JSON manifest.  The primary checker compares this record only after this
# module has validated it on its own terms.
DIRECT_SPECS = {
    "AR-PSL2-ODD": {
        "domain": {"rank": None, "f_min": 1, "f_parity": "any",
                   "p_mode": "odd", "q_min": 13},
        "obstruction": {"prime": "p", "group_valuation": "f",
                        "subgroup_valuations": [0, 0],
                        "outer_divisor": "2f",
                        "universal_fact": "v_p(f)<f for f>0"},
    },
    "AR-ALTERNATING": {
        "domain": {"rank": {"variable": "n", "min": 15, "parity": "any"},
                   "f_min": None, "f_parity": None,
                   "p_mode": "selected-largest-prime", "q_min": None},
        "obstruction": {"prime_condition": "n/2<p<=n", "group_valuation": 1,
                        "subgroup_valuations": [0, 0], "outer_divisor": 2,
                        "class_count_condition": "p>=n/2+3"},
        "large_range": {"n_min": 31, "source": "Nagura",
                        "inequality": "5n/6<p<=n"},
        "finite_range": {"n_min": 15, "n_max": 30,
                         "largest_primes": [13, 13, 17, 17, 19, 19, 19, 19,
                                            23, 23, 23, 23, 23, 23, 29, 29]},
    },
}


def parity_ok(value: int, parity: str) -> bool:
    return parity == "any" or (parity == "odd" and value % 2 == 1) or (
        parity == "even" and value % 2 == 0
    )


def universal_lt(low: Lin, high: Lin, case: PrimitiveCase) -> None:
    if case.n_kind in {"none", "fixed"}:
        assert 0 < low.at(case.n0) < high.at(case.n0), case.key
    else:
        diff = Lin(high.a - low.a, high.b - low.b)
        assert low.at(case.n0) > 0 and diff.a >= 0 and diff.at(case.n0) > 0, case.key


def min_e(case: PrimitiveCase) -> int:
    return case.exponent.at(case.n0) * case.f0


def factors(n: int) -> set[int]:
    ans = set()
    d = 2
    while d * d <= n:
        while n % d == 0:
            ans.add(d)
            n //= d
        d += 1
    if n > 1:
        ans.add(n)
    return ans


def solve_exception(case: PrimitiveCase) -> tuple[tuple[int | None, int], ...]:
    if not case.characteristic_two_allowed:
        return ()
    if case.n_kind == "none":
        ns: tuple[int | None, ...] = (None,)
    elif case.n_kind == "fixed":
        ns = (case.n0,)
    else:
        # E=6 and f>=1 imply a*n+b<=6.  Thus the following upper bound is
        # exhaustive, not a heuristic parameter cutoff.
        assert case.exponent.a > 0
        upper = (6 - case.exponent.b) // case.exponent.a
        ns = tuple(n for n in range(case.n0, upper + 1) if parity_ok(n, case.n_parity))
    out = []
    for n in ns:
        coefficient = case.exponent.at(0 if n is None else n)
        for f in range(case.f0, 7):
            if parity_ok(f, case.f_parity) and coefficient * f == 6:
                out.append((n, f))
    return tuple(out)


def verify_primitive_cases() -> int:
    assert len(CASES) == 32 and len({c.key for c in CASES}) == 32
    assert ("AR-PSL2-ODD",) + tuple(c.key for c in CASES[:1]) + ("AR-ALTERNATING",) + tuple(c.key for c in CASES[1:]) == EXPECTED_KEYS
    inequalities = 0
    for case in CASES:
        assert case.n_kind in {"none", "fixed", "variable"}
        assert min_e(case) >= 3
        expected_group = case.group_q_exponent.twice() if case.group_kind == "plus" else case.group_q_exponent
        assert case.group_kind in {"minus", "plus", "cyclotomic"}
        assert case.exponent == expected_group, case.key
        assert len(case.selected) == len(case.selected_constants) >= 2
        for bounds, constants in zip(case.selected, case.selected_constants):
            assert bounds
            for bound in bounds:
                universal_lt(bound, case.exponent, case)
                inequalities += 1
            assert all(max(factors(c), default=1) <= min_e(case) for c in constants)
        for diag in case.diagonal:
            universal_lt(diag, case.exponent, case)
            inequalities += 1
        for central in case.central:
            universal_lt(central, case.exponent, case)
            inequalities += 1
        if case.outer_kind == "size":
            diff = Lin(case.exponent.a, case.exponent.b - case.outer_constant)
            assert (case.n_kind != "variable" and diff.at(case.n0) >= 0) or (
                case.n_kind == "variable" and diff.a >= 0 and diff.at(case.n0) >= 0
            ), case.key
        else:
            assert case.outer_kind == "factor"
            assert max(factors(case.outer_constant), default=1) <= min_e(case), case.key
        assert solve_exception(case) == case.exception_points, case.key
    return inequalities


def polynomial_special_residues() -> None:
    # Coefficients are in ascending order.  These exact polynomial identities
    # prove that each common divisor in the two special branches divides 2.
    def sub(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
        m = max(len(a), len(b))
        out = tuple((a[i] if i < len(a) else 0) - (b[i] if i < len(b) else 0) for i in range(m))
        while len(out) > 1 and out[-1] == 0:
            out = out[:-1]
        return out

    def mul(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
        out = [0] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            for j, y in enumerate(b):
                out[i + j] += x * y
        return tuple(out)

    # q^2+1 - (q+1)(q-1) = 2 (Sp4 odd graph-field branch).
    assert sub((1, 0, 1), mul((1, 1), (-1, 1))) == (2,)
    # q^3+1 - (q^3-1) = 2 (G2 odd graph-field branch).
    assert sub((1, 0, 0, 1), (-1, 0, 0, 1)) == (2,)


def vp(n: int, p: int) -> int:
    out = 0
    while n and n % p == 0:
        out += 1
        n //= p
    return out


def gl_order(n: int, q: int) -> int:
    return q ** (n * (n - 1) // 2) * prod(q ** i - 1 for i in range(1, n + 1))


def sl_order(n: int, q: int) -> int:
    return q ** (n * (n - 1) // 2) * prod(q ** i - 1 for i in range(2, n + 1))


def omega_plus_order(n: int, q: int) -> int:
    return q ** (n * (n - 1)) * (q ** n - 1) * prod(q ** (2 * i) - 1 for i in range(1, n))


def sp_order(n: int, q: int) -> int:
    return q ** (n * n) * prod(q ** (2 * i) - 1 for i in range(1, n + 1))


def substitute_valuations() -> tuple[dict, ...]:
    # PSL(2,8), r=3.
    q = 8
    s = q * (q ** 2 - 1)
    borel = q * (q - 1)
    split_torus_normalizer = 2 * (q - 1)
    assert vp(s, 3) == 2
    assert vp(borel, 3) == vp(split_torus_normalizer, 3) == 0
    assert 2 > vp(3, 3) == 1

    # PSL(6,2), r=31, independently evaluate both graph routes.
    s = sl_order(6, 2)
    psl_p2 = gl_order(2, 2) * gl_order(4, 2)
    psl_p3 = gl_order(3, 2) ** 2
    flag1 = gl_order(4, 2)
    flag2 = gl_order(2, 2) ** 3
    assert vp(s, 31) == 1
    assert all(vp(v, 31) == 0 for v in (psl_p2, psl_p3, flag1, flag2))
    assert vp(2, 31) == 0

    # Omega^+(8,2), r=5, independently evaluate ordinary and triality pairs.
    s = omega_plus_order(4, 2)
    trial1 = gl_order(2, 2) ** 3
    trial2 = gl_order(2, 2)
    d_p1 = omega_plus_order(3, 2)
    d_p2 = gl_order(2, 2) * omega_plus_order(2, 2)
    assert vp(s, 5) == 2
    assert vp(trial1, 5) == vp(trial2, 5) == 0
    assert vp(s, 5) - vp(d_p1, 5) - vp(d_p2, 5) == 1 > vp(24, 5)

    # Sp(4,8), r=3.
    q = 8
    s = sp_order(2, q)
    sp_borel = q ** 4 * (q - 1) ** 2
    sp_suzuki = q ** 2 * (q ** 2 + 1) * (q - 1)
    assert vp(s, 3) == 4 and vp(sp_borel, 3) == vp(sp_suzuki, 3) == 0
    assert 4 > vp(6, 3) == 1

    return (
        {"id": "SUB-PSL2-8", "exception_id": "Z-PSL2-8",
         "branch_ids": ["AR-PSL2-EVEN"], "prime": 3, "group_order": 504,
         "subgroup_orders": [56, 14], "outer_multiple": 3, "required_gap": 1},
        {"id": "SUB-PSL6-2-A", "exception_id": "Z-PSL6-2",
         "branch_ids": ["AR-PSL-TRIVIAL"], "prime": 31,
         "group_order": sl_order(6, 2), "subgroup_orders": [psl_p2, psl_p3],
         "outer_multiple": 2, "required_gap": 0},
        {"id": "SUB-PSL6-2-B", "exception_id": "Z-PSL6-2",
         "branch_ids": ["AR-PSLN-GRAPH"], "prime": 31,
         "group_order": sl_order(6, 2), "subgroup_orders": [flag1, flag2],
         "outer_multiple": 2, "required_gap": 0},
        {"id": "SUB-D4-2-ORDINARY", "exception_id": "Z-D4-2",
         "branch_ids": ["AR-DPLUS"], "prime": 5,
         "group_order": omega_plus_order(4, 2), "subgroup_orders": [d_p1, d_p2],
         "outer_multiple": 24, "required_gap": 0},
        {"id": "SUB-D4-2-TRIALITY", "exception_id": "Z-D4-2",
         "branch_ids": ["AR-D4-TRIALITY"], "prime": 5,
         "group_order": omega_plus_order(4, 2),
         "subgroup_orders": [trial1, trial2], "outer_multiple": 24,
         "required_gap": 0},
        {"id": "SUB-SP4-8", "exception_id": "Z-SP4-8",
         "branch_ids": ["AR-SP4-GRAPH-ODD"], "prime": 3,
         "group_order": sp_order(2, 8), "subgroup_orders": [sp_borel, sp_suzuki],
         "outer_multiple": 6, "required_gap": 1},
    )


def is_prime(n: int) -> bool:
    return n >= 2 and all(n % d for d in range(2, isqrt(n) + 1))


def direct_branches() -> None:
    # PSL(2,q), q odd: mathlib kernel-checks padicValNat p f < f for every
    # f>0; the formula inputs give group valuation f, subgroup valuations 0,
    # and x|2f.  Here we independently pin the exact branch hypotheses.
    psl2 = DIRECT_SPECS["AR-PSL2-ODD"]
    assert psl2["domain"]["f_min"] == 1 and psl2["domain"]["p_mode"] == "odd"
    assert psl2["obstruction"]["universal_fact"] == "v_p(f)<f for f>0"
    assert all(vp(f, p) < f for p in (3, 5, 7, 11) for f in range(1, 128))

    # A_n, n=15..30: exact largest-prime list and valuation/class bound.
    alternating = DIRECT_SPECS["AR-ALTERNATING"]
    ps = tuple(alternating["finite_range"]["largest_primes"])
    for n, p in zip(range(15, 31), ps):
        assert is_prime(p) and p <= n
        assert not any(is_prime(k) for k in range(p + 1, n + 1))
        assert 2 * p >= n + 6 and n < 2 * p
    # For n>=31, Nagura gives 6p>5n.  The coefficient certificate below is
    # the universal linear deduction 12p>10n>=6n+36.
    assert alternating["large_range"] == {
        "n_min": 31, "source": "Nagura", "inequality": "5n/6<p<=n"
    }
    assert 4 * alternating["large_range"]["n_min"] > 36


def main() -> int:
    inequalities = verify_primitive_cases()
    polynomial_special_residues()
    substitute_valuations()
    direct_branches()
    print("exact theorem branches independently encoded: 34")
    print(f"primitive branches universally checked: {len(CASES)}")
    print(f"source-derived exponent/diagonal bounds proved: {inequalities}")
    print("special residue identities: Sp4 odd, G2 odd: PASS")
    print("substitute-prime exact valuations: PSL(2,8), PSL(6,2) x2, Omega+(8,2) x2, Sp(4,8): PASS")
    print("defining-characteristic and alternating universal lemmas: PASS")
    print("INDEPENDENT SYMBOLIC FAMILY ARITHMETIC|PASS")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (AssertionError, ArithmeticError, ValueError) as exc:
        raise SystemExit("HARD-FAIL: " + str(exc))
